---
platform: linux
image: docker://140.211.168.166:5000/golang1.6

inputs:
- name: archive-resource
  path: gopath/src/github.com/concourse/archive-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/archive-resource/scripts/ci
