---
platform: linux
image: docker:///mischief/docker-golang

inputs:
- name: archive-resource
  path: gopath/src/github.com/concourse/archive-resource

run:
  path: gopath/src/github.com/concourse/archive-resource/scripts/test
