---
platform: linux
image: docker:///golang#1.5

inputs:
- name: archive-resource
  path: gopath/src/github.com/concourse/archive-resource

run:
  path: gopath/src/github.com/concourse/archive-resource/scripts/test
